enum GSActionType {
  // SCENE ACTIONS
  INIT_SCENE,
  SPEECH,
  ASSIGN_VARIABLE_VALUE,
  SOUND,
  SET_BACKGROUND,
  DEFINE_ANCHOR,
  JUMP,
  WAIT,
  // ASSIGN ACTIONS
  ASSIGN_CHARACTER,
  // CHARACTER ACTIONS
  SHOW_CHARACTER,
  HIDE_CHARACTER,
}